import type { Feature } from "../types.js";
import { hasFeature } from "../utils.js";

export function buildCloudflareEnvDts(features: Feature[]): string {
	const bindings: string[] = ["\tASSETS: Fetcher;"];

	if (hasFeature(features, "drizzle")) {
		bindings.push("\tDB: D1Database;");
	}

	if (hasFeature(features, "auth")) {
		bindings.push("\tKV: KVNamespace;");
	}

	if (hasFeature(features, "r2")) {
		bindings.push("\tSTORAGE: R2Bucket;");
	}

	if (hasFeature(features, "queues")) {
		bindings.push("\tQUEUE: Queue;");
	}

	return `// Generated by create-ncf. Run \`wrangler types\` to regenerate with full Cloudflare types.
/// <reference types="@cloudflare/workers-types" />

interface CloudflareEnv {
${bindings.join("\n")}
}
`;
}

export function buildLibEnvDts(features: Feature[]): string {
	const entries: string[] = [];

	if (hasFeature(features, "drizzle")) {
		entries.push("\t\tDB: D1Database;");
	}

	if (hasFeature(features, "auth")) {
		entries.push("\t\tKV: KVNamespace;");
	}

	if (hasFeature(features, "r2")) {
		entries.push("\t\tSTORAGE: R2Bucket;");
	}

	if (hasFeature(features, "queues")) {
		entries.push("\t\tQUEUE: Queue;");
	}

	if (entries.length === 0) {
		return `declare namespace NodeJS {
\tinterface ProcessEnv {
\t\t[key: string]: string | undefined;
\t}
}
`;
	}

	return `declare namespace NodeJS {
\tinterface ProcessEnv {
${entries.join("\n")}
\t\t[key: string]: string | undefined;
\t}
}
`;
}
