import type { Feature } from "../types.js";
import { hasFeature } from "../utils.js";

export function buildWorkerTs(features: Feature[]): string {
	const lines: string[] = [
		"// @ts-ignore — .open-next is generated by opennextjs-cloudflare build",
		'import openNextWorker from "./.open-next/worker";',
		"",
		"// Durable Objects exported from the package directly",
		'export { BucketCachePurge } from "@opennextjs/cloudflare/durable-objects/bucket-cache-purge";',
		'export { DOQueueHandler } from "@opennextjs/cloudflare/durable-objects/queue";',
		'export { DOShardedTagCache } from "@opennextjs/cloudflare/durable-objects/sharded-tag-cache";',
	];

	if (hasFeature(features, "queues")) {
		lines.push(
			"",
			"async function handleQueue(",
			"\tbatch: MessageBatch<unknown>,",
			"\tenv: CloudflareEnv,",
			") {",
			"\t// Bridge Cloudflare env vars to process.env so modules importing ~/env work.",
			"\tfor (const [key, value] of Object.entries(env)) {",
			'\t\tif (typeof value === "string") {',
			"\t\t\tprocess.env[key] = value;",
			"\t\t}",
			"\t}",
			"",
			'\tconst { handleBatch, handleDlqBatch } = await import("./src/server/queues/handler");',
			"",
			`\tif (batch.queue.endsWith("-dlq")) {`,
			"\t\tawait handleDlqBatch(batch, env);",
			"\t\treturn;",
			"\t}",
			"",
			"\tawait handleBatch(batch, env);",
			"}",
		);
	}

	lines.push("", "export default {");
	lines.push(
		"\tfetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {",
		"\t\treturn openNextWorker.fetch(request, env, ctx);",
		"\t},",
	);

	if (hasFeature(features, "queues")) {
		lines.push(
			"\tasync queue(batch: MessageBatch<unknown>, env: CloudflareEnv) {",
			"\t\tawait handleQueue(batch, env);",
			"\t},",
		);
	}

	lines.push("};");

	return lines.join("\n");
}
